"""Tiny LDraw helper: part lookup, bounding boxes, and model writing.

Units are LDraw units (LDU): 1 stud = 20, 1 plate = 8, 1 brick = 24.
LDraw's -Y is up. Model convention used by the build scripts:
    X = rig length (0 = front bumper face, + toward the rear)
    Z = width (0 = centreline)
    Y = -height (ground is Y = 0)
"""
from __future__ import annotations

import functools
import os
from dataclasses import dataclass, field

import numpy as np

LIB = os.environ.get("LDRAWDIR", "/usr/share/ldraw")
SEARCH = ["parts", "p", "parts/s", "p/48", "p/8", "models"]

STUD, PLATE, BRICK = 20, 8, 24


def find(name: str) -> str | None:
    name = name.replace("\\", "/").lower()
    for d in SEARCH:
        p = os.path.join(LIB, d, name)
        if os.path.exists(p):
            return p
    return None


@functools.lru_cache(maxsize=None)
def title(name: str) -> str:
    p = find(name)
    if not p:
        return "?"
    with open(p, errors="replace") as f:
        return f.readline()[2:].strip()


@functools.lru_cache(maxsize=None)
def bbox(name: str):
    """Axis-aligned bbox (min xyz, max xyz) of a part in its own coordinates."""
    p = find(name)
    if not p:
        raise FileNotFoundError(name)
    pts = []
    with open(p, errors="replace") as f:
        for line in f:
            t = line.split()
            if not t:
                continue
            if t[0] in ("2", "3", "4", "5"):
                v = [float(x) for x in t[2:]]
                if t[0] == "5":
                    v = v[:6]
                pts.extend(np.array(v).reshape(-1, 3))
            elif t[0] == "1":
                m = [float(x) for x in t[2:14]]
                pos = np.array(m[0:3])
                rot = np.array(m[3:12]).reshape(3, 3)
                try:
                    lo, hi = bbox(" ".join(t[14:]))
                except FileNotFoundError:
                    continue
                corners = np.array([[x, y, z] for x in (lo[0], hi[0]) for y in (lo[1], hi[1]) for z in (lo[2], hi[2])])
                pts.extend(corners @ rot.T + pos)
    if not pts:
        z = np.zeros(3)
        return z, z
    a = np.array(pts)
    return a.min(axis=0), a.max(axis=0)


# ---- rotations (LDraw row-major 3x3) ----
I = np.eye(3)


def rot_y(deg):
    r = np.radians(deg)
    c, s = round(np.cos(r), 6), round(np.sin(r), 6)
    return np.array([[c, 0, s], [0, 1, 0], [-s, 0, c]])


def rot_x(deg):
    r = np.radians(deg)
    c, s = round(np.cos(r), 6), round(np.sin(r), 6)
    return np.array([[1, 0, 0], [0, c, -s], [0, s, c]])


def rot_z(deg):
    r = np.radians(deg)
    c, s = round(np.cos(r), 6), round(np.sin(r), 6)
    return np.array([[c, -s, 0], [s, c, 0], [0, 0, 1]])


@dataclass
class Part:
    part: str
    color: int
    pos: tuple
    rot: np.ndarray = field(default_factory=lambda: I.copy())
    note: str = ""

    def line(self) -> str:
        x, y, z = (float(v) for v in self.pos)
        m = " ".join(_fmt(v) for v in self.rot.reshape(-1))
        return f"1 {self.color} {_fmt(x)} {_fmt(y)} {_fmt(z)} {m} {self.part}"

    def world_bbox(self):
        lo, hi = bbox(self.part) if self.part.endswith(".dat") else (np.zeros(3), np.zeros(3))
        corners = np.array([[x, y, z] for x in (lo[0], hi[0]) for y in (lo[1], hi[1]) for z in (lo[2], hi[2])])
        w = corners @ self.rot.T + np.array(self.pos, dtype=float)
        return w.min(axis=0), w.max(axis=0)


def _fmt(v: float) -> str:
    v = round(float(v), 4)
    return str(int(v)) if v == int(v) else f"{v:g}"


class Model:
    """An LDraw (sub)model: a list of parts grouped into build steps."""

    def __init__(self, name: str, title_: str):
        self.name, self.title = name, title_
        self.steps: list[list[Part | str]] = [[]]

    def add(self, part, color, pos, rot=None, note=""):
        p = Part(part, color, tuple(pos), I.copy() if rot is None else rot, note)
        self.steps[-1].append(p)
        return p

    def sub(self, model: "Model", pos=(0, 0, 0), rot=None, color=16):
        p = Part(model.name, color, tuple(pos), I.copy() if rot is None else rot)
        self.steps[-1].append(p)
        return p

    def step(self):
        if self.steps[-1]:
            self.steps.append([])

    def parts(self):
        return [p for s in self.steps for p in s if isinstance(p, Part)]

    def text(self) -> str:
        out = [f"0 FILE {self.name}", f"0 {self.title}", f"0 Name: {self.name}",
               "0 Author: Claude Code (generated by tools/build_*.py)"]
        steps = [s for s in self.steps if s]
        for i, s in enumerate(steps):
            out += [p.line() for p in s]
            out.append("0 STEP")
        return "\n".join(out) + "\n"


def write_mpd(path: str, models: list[Model]):
    with open(path, "w") as f:
        f.write("\n".join(m.text() for m in models))


def overlaps(parts: list[Part], tol=1.0, ignore=lambda a, b: False):
    """Report pairs whose bboxes overlap by more than tol LDU on every axis.

    Bounding boxes are coarse (studs, round parts), so this only catches
    gross placement errors, not real interference.
    """
    boxes = [(p, *p.world_bbox()) for p in parts]
    hits = []
    for i in range(len(boxes)):
        a, alo, ahi = boxes[i]
        for j in range(i + 1, len(boxes)):
            b, blo, bhi = boxes[j]
            if ignore(a, b):
                continue
            ov = np.minimum(ahi, bhi) - np.maximum(alo, blo)
            if (ov > tol).all():
                hits.append((a, b, ov))
    return hits
